export const FAKE_POPULARS = [
  {
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    first_air_date: "2023-01-15",
    genre_ids: [18, 10759],
    id: 100088,
    name: "The Last of Us The Last of UsThe Last of Us",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    popularity: 4048.077,
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    vote_average: 7.1,
    vote_count: 1525,
  },
];
export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/mNHRGO1gFpR2CYZdANe72kcKq7G.jpg",
    id: 153312,
    name: "Tulsa King",
    original_language: "en",
    original_name: "Tulsa King",
    overview:
      "Just after he is released from prison after 25 years, New York mafia capo Dwight “The General” Manfredi is unceremoniously exiled by his boss to set up shop in Tulsa, Okla. Realizing that his mob family may not have his best interests in mind, Dwight slowly builds a “crew” from a group of unlikely characters, to help him establish a new criminal empire in a place that to him might as well be another planet.",
    poster_path: "/fwTv3RPRAIy0maOMns5eYRRwnDk.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 1328.156,
    first_air_date: "2022-11-13",
    vote_average: 8.541,
    vote_count: 786,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    id: 119051,
    name: "Wednesday",
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 35],
    popularity: 1161.17,
    first_air_date: "2022-11-23",
    vote_average: 8.658,
    vote_count: 6300,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 532.68,
    first_air_date: "2011-04-17",
    vote_average: 8.4,
    vote_count: 20533,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mYegNdFjJeCISA1RDDCKBhKB4Ao.jpg",
    id: 126725,
    name: "Velma",
    original_language: "en",
    original_name: "Velma",
    overview:
      "Jinkies! This raucous reimagining of the Scooby-Doo franchise unravels the mysterious origins of Mystery, Inc. – as seen through the eyes of the gang’s beloved bespectacled detective Velma.",
    poster_path: "/zxkNhuPSHeDv3yA7sFu2RuEOGgR.jpg",
    media_type: "tv",
    genre_ids: [16, 35],
    popularity: 276.263,
    first_air_date: "2023-01-12",
    vote_average: 2.827,
    vote_count: 81,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 299.988,
    first_air_date: "2016-07-15",
    vote_average: 8.637,
    vote_count: 15068,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/xZUZ9i6vVayjyhR1vRo9Bjku4h.jpg",
    id: 63174,
    name: "Lucifer",
    original_language: "en",
    original_name: "Lucifer",
    overview:
      "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    poster_path: "/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
    media_type: "tv",
    genre_ids: [80, 10765],
    popularity: 544.202,
    first_air_date: "2016-01-25",
    vote_average: 8.5,
    vote_count: 13161,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/kSqEenES71d1ApF2rRWxp5X0en5.jpg",
    id: 156902,
    name: "Kaleidoscope",
    original_language: "en",
    original_name: "Kaleidoscope",
    overview:
      "A master thief and his crew attempt an epic and elaborate heist worth $7 billion dollars — but betrayal, greed and other threats undermine their plans.",
    poster_path: "/2nXJoSB5Y6R9ne7pjqL7Cs3zqY1.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 174.584,
    first_air_date: "2023-01-01",
    vote_average: 7.292,
    vote_count: 180,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/5DUMPBSnHOZsbBv81GFXZXvDpo6.jpg",
    id: 114410,
    name: "Chainsaw Man",
    original_language: "ja",
    original_name: "チェンソーマン",
    overview:
      "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.",
    poster_path: "/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
    media_type: "tv",
    genre_ids: [16, 10759, 10765, 35],
    popularity: 595.36,
    first_air_date: "2022-10-12",
    vote_average: 8.718,
    vote_count: 840,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/gQxaF79LUTtopdYHsuS8lUr9rvF.jpg",
    id: 97951,
    name: "Mayor of Kingstown",
    original_language: "en",
    original_name: "Mayor of Kingstown",
    overview:
      "In a small Michigan town where the business of incarceration is the only thriving industry, the McClusky family are the power brokers between the police, criminals, inmates, prison guards and politicians in a city completely dependent on prisons and the prisoners they contain.",
    poster_path: "/86OUOPulMiM8rjrQSt4KMev7UAa.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 94.211,
    first_air_date: "2021-11-14",
    vote_average: 8.254,
    vote_count: 114,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rAZj3toS3GErvpRgoK4R4fFaGFq.jpg",
    id: 137437,
    name: "National Treasure: Edge of History",
    original_language: "en",
    original_name: "National Treasure: Edge of History",
    overview: "While searching for history's greatest treasure, Jess Valenzuela unburies her family's secret past.",
    poster_path: "/noRVimjdx6PwPBCVikhExYqogsX.jpg",
    media_type: "tv",
    genre_ids: [10759],
    popularity: 220.136,
    first_air_date: "2022-12-14",
    vote_average: 7.2,
    vote_count: 84,
    origin_country: ["US"],
  },
];
